### ISSUE TITLE
Sniff fails to run command on first run.

### ISSUE THREAD

**Issue by rv178** [Shinyzenith/sniff#1]
**Sniff fails to run given command on first run.**

__Steps to reproduce the behavior__

1. Create a sniff.json in the root directory and edit it.

In my case:
```json
{
  ".*.rs": ["cargo clippy", "cargo check", "cargo build --release"]
}
```
2. Copy sniff's binary to project's root directory.
3. Run the binary.
4. Edit required files and save.

__Expected behavior__

Sniff runs the command specified in `sniff.json` on file change.

__Resulting behavior__

Sniff does not run the command specified in `sniff.json` the first time one saves the file. However, it is observed that sniff runs the command on later saves.

**Comment by Shinyzenith** [comment]
I can reproduce this error.

**Comment by Shinyzenith** [comment]
I added some debug code to sniff and apparently if nothing is changed in the file and then saved, vim doesn't trigger a NoticeWrite or Write, hence no execution ( I assume other popular editors do the same ).

I will eventually make these events configurable too so you can pick and choose. 
Closing as NAB.

**Comment by rv178** [comment]
> nothing is changed in the file

I did mention that in order to reproduce this behavior, one has to edit the file and then save it. Anyhow, thank you for looking into the issue!

**Comment by Shinyzenith** [comment]
> > nothing is changed in the file
> 
> I did mention that in order to reproduce this behavior, one has to edit the file and then save it. Anyhow, thank you for looking into the issue!

I'd suggest you test it again.
